Repository Team-Ampersand/Dotori-server-V2, pull requests merged in 2023-07, with the labels that each got.

#228 227 feat/build src query dsl
  DockerfileDev
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt
  src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/SearchStudentServiceImpl.kt
Labels: feature

#232 개발 브랜치를 마스터브랜치에 머지
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: Priority : Critical

#234 🔀 :: 233 - 일요일에 자습신청, 취소가 되면 안됨
  src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt
Labels: Priority : Critical

#236 #229 유저 검색 서비스 QueryDSL 적용
  build.gradle.kts
  src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepository.kt
  src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepositoryImpl.kt
  src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt
  src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/FindAllMemberServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/SearchStudentServiceImpl.kt
  src/main/kotlin/com/dotori/v2/global/config/querydsl/QueryDSLConfig.kt
Labels: Priority : High

#238 237 feat/get self study querydsl
  .github/CODEOWNERS
  src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepository.kt
  src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepositoryImpl.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumAndNameServiceImpl.kt
Labels: Priority : High
