Repository Team-Ampersand/Dotori-server-V2, pull requests merged in 2023-05, with the labels that each got.

#206 🔀 ::205 - SelfStudyCheckUtil 테스트 코드 작성
  src/test/kotlin/com/dotori/v2/domain/self_study/util/SelfStudyCheckUtilTest.kt
Labels: feature, Priority : Medium

#211 🔀 :: 209 - 서비스 테스트 코드에 util 적용
  src/test/kotlin/com/dotori/v2/domain/main_page/service/GetPersonalInfoServiceTest.kt
Labels: Priority : Medium

#214 🔀 :: 자습신청 일요일 검증 로직 제거
  src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/util/ValidaDayOfWeekAndHourTest.kt
Labels: Priority : High

#217 🔀 :: 216 - 안마의자 신청 테스트 코드
  src/test/kotlin/com/dotori/v2/domain/massage/controller/MassageApplyControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/massage/service/MassageApplyServiceTest.kt
Labels: feature, Priority : Medium

#219 🔀 :: 218 - 안마의자 정보 테스트
  src/test/kotlin/com/dotori/v2/domain/massage/controller/GetMassageInfoControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/massage/service/GetMassageInfoServiceTest.kt
Labels: feature, Priority : Medium

#222 🔀 :: 221 - 안마의자 제한수 수정 테스트 코드
  src/test/kotlin/com/dotori/v2/domain/massage/controller/UpdateMassageLimitControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/massage/service/UpdateMassageLimitServiceTest.kt
Labels: feature, Priority : Medium

#224 🔨 :: 223 - 조건문에서 잘못 검사하고 있던 부분 수정
  src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt
Labels: bug, Priority : Critical
