Repository Team-Ampersand/Dotori-server-V2, pull requests merged in 2023-03, with the labels that each got.

#32 공지사항 작성 기능 구현
  build.gradle.kts
  src/main/kotlin/com/dotori/v2/domain/board/presentation/admin/AdminBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/councillor/CouncillorBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/data/dto/CreateBoardDto.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/data/req/CreateBoardReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/developer/DeveloperBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/CreateBoardService.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/S3Service.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/CreateBoardServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/S3ServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/board/util/BoardSaveUtil.kt
  src/main/kotlin/com/dotori/v2/global/config/aws/AwsS3Config.kt
  src/test/kotlin/com/dotori/v2/domain/board/controller/CreateBoardControllerTest.kt
Labels: feature, Priority : High

#37 🔀 :: 36-자습관련 스케줄 객체, util객체
  src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
  src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/dev/SelfStudyCountConfig.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/domain/entity/SelfStudyCount.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/schedule/SelfStudySchedule.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/UpdateSelfStudyStatusService.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/UpdateSelfStudyStatusServiceImpl.kt
Labels: feature, Priority : High

#41 🔀 :: 40-공지사항 삭제 기능 구현
  src/main/kotlin/com/dotori/v2/domain/board/domain/repository/BoardImageRepository.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/admin/AdminBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/councillor/CouncillorBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/developer/DeveloperBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/DeleteBoardService.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/DeleteBoardServiceImpl.kt
  src/test/kotlin/com/dotori/v2/domain/board/controller/CreateBoardControllerTest.kt
Labels: feature, Priority : High

#44 🔀 :: 42-공지사항 전체 조회 기능 구현
  src/main/kotlin/com/dotori/v2/domain/board/presentation/admin/AdminBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/councillor/CouncillorBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/BoardResDto.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/ListBoardResDto.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/developer/DeveloperBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/member/MemberBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/GetBoardsService.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardsServiceImpl.kt
  src/test/kotlin/com/dotori/v2/domain/board/controller/CreateBoardControllerTest.kt
Labels: Priority : High

#47 🔀 :: 44-전체조회의 페이징을 추가하였습니다
  src/main/kotlin/com/dotori/v2/domain/board/presentation/admin/AdminBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/councillor/CouncillorBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/developer/DeveloperBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/member/MemberBoardController.kt
Labels: feature, Priority : High

#49 🔀 :: 48-공지사항 상세정보 기능 개발
  src/main/kotlin/com/dotori/v2/domain/board/domain/repository/BoardImageRepository.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/admin/AdminBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/councillor/CouncillorBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/DetailBoardResDto.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/developer/DeveloperBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/member/MemberBoardController.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/GetBoardDetailService.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/DeleteBoardServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardDetailServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardsServiceImpl.kt
Labels: feature, Priority : High

#51 🔀 :: 50-기상음악 신청 기능 구현
  src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
  src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
  src/main/kotlin/com/dotori/v2/domain/music/exception/MusicAlreadyException.kt
  src/main/kotlin/com/dotori/v2/domain/music/exception/MusicCantRequestDateException.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/councillor/CouncillorMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/data/dto/ApplyMusicDto.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/data/req/ApplyMusicReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/developer/DeveloperMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/member/MemberMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/schedule/MusicSchedule.kt
  src/main/kotlin/com/dotori/v2/domain/music/service/ApplyMusicService.kt
  src/main/kotlin/com/dotori/v2/domain/music/service/impl/ApplyMusicServiceImpl.kt
Labels: feature, Priority : High

#53 🔀 :: 51-스케쥴링 안되던 버그를 고쳤습니다
  build.gradle.kts
  src/main/kotlin/com/dotori/v2/V2Application.kt
  src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
  src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/admin/AdminMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/data/res/MusicListResDto.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/data/res/MusicResDto.kt
  src/main/kotlin/com/dotori/v2/domain/music/schedule/MusicSchedule.kt
  src/main/kotlin/com/dotori/v2/domain/music/service/FindMusicsService.kt
  src/main/kotlin/com/dotori/v2/domain/music/service/impl/FindMusicsServiceImpl.kt
Labels: bug, Priority : Critical

#56 🔀 쿼리문 변경 및 타입을 변경하였습니다
  src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/admin/AdminMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/service/FindMusicsService.kt
  src/main/kotlin/com/dotori/v2/domain/music/service/impl/FindMusicsServiceImpl.kt
Labels: bug, Priority : Critical

#58 🔀 :: 57-음악 조회 부분이 어드민에만 적용되었던것을 다른 곳에도 추가
  src/main/kotlin/com/dotori/v2/domain/music/presentation/councillor/CouncillorMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/developer/DeveloperMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/member/MemberMusicController.kt
  src/test/kotlin/com/dotori/v2/domain/board/controller/CreateBoardControllerTest.kt
Labels: bug, Priority : Critical

#60 🔀 :: 59-음악 개별 삭제 기능을 개발하였습니다
  src/main/kotlin/com/dotori/v2/domain/music/exception/MusicNotFoundException.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/admin/AdminMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/councillor/CouncillorMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/presentation/developer/DeveloperMusicController.kt
  src/main/kotlin/com/dotori/v2/domain/music/service/DeleteMusicService.kt
  src/main/kotlin/com/dotori/v2/domain/music/service/impl/DeleteMusicServiceImpl.kt
Labels: feature, Priority : High

#63 🔀 :: 62-안마의자 신청 API개발
  src/main/kotlin/com/dotori/v2/domain/massage/dev/MassageCountConfig.kt
  src/main/kotlin/com/dotori/v2/domain/massage/domain/entity/MassageCount.kt
  src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageCountRepository.kt
  src/main/kotlin/com/dotori/v2/domain/massage/exception/AlreadyApplyMassageException.kt
  src/main/kotlin/com/dotori/v2/domain/massage/exception/SelfStudyOverException.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/ApplyMassageService.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/massage/util/FindMassageCountUtil.kt
  src/main/kotlin/com/dotori/v2/domain/massage/util/MassageCheckUtil.kt
  src/main/kotlin/com/dotori/v2/domain/massage/util/SaveMassageUtil.kt
  src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourUtil.kt
  src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
Labels: feature, Priority : High

#65 🔀 규정위반 부여 기능 구현
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt
  src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt
  src/main/kotlin/com/dotori/v2/domain/rule/presentation/admin/AdminRuleController.kt
  src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/dto/RuleGrantDto.kt
  src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/req/RuleGrantReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/InsertRuleService.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/impl/InsertRuleServiceImpl.kt
Labels: feature, Priority : High

#69 🔀 :: 68-안마의자 신청한 학생 전체 조회
  src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageRepository.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/admin/AdminMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/councillor/CouncillorMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/developer/DeveloperMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageMemberListResDto.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageMemberResDto.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/member/MemberMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/GetMassageRankService.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/GetMassageRankServiceImpl.kt
Labels: feature, Priority : High

#71 🔀 :: 70 - 조회할때 idx추가
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/res/SelfStudyMemberResDto.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByMemberNameServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyRankServiceImpl.kt
Labels: feature, Priority : High

#76 🔀 :: 72 - 마사지 정보 조회
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/admin/AdminMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/councillor/CouncillorMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/developer/DeveloperMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageInfoResDto.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/member/MemberMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/GetMassageInfoService.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/GetMassageInfoServiceImpl.kt
Labels: feature, Priority : High

#78 🔀 :: 77 - 안마의자 스케줄
  src/main/kotlin/com/dotori/v2/domain/massage/schedule/MassageSchedule.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/UpdateMassageStatusService.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/UpdateMassageStatusServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt
  src/main/kotlin/com/dotori/v2/domain/member/presentation/data/req/SignupReqDto.kt
Labels: feature, Priority : High

#80 🔀 :: 79-CICD를 만들었습니다
  .github/workflows/develop.yml
  .github/workflows/master.yml
  Dockerfile
  src/test/kotlin/com/dotori/v2/V2ApplicationTests.kt
  src/test/kotlin/com/dotori/v2/domain/board/controller/CreateBoardControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/main_page/service/BoardAlarmServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/main_page/service/GetPersonalInfoServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/member/service/LogoutServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/member/service/RefreshTokenServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/member/service/WithdrawalServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/ApplySelfStudyServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/CancelSelfStudyServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyInfoServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyMemberNameServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyStuNumServiceTest.kt
Labels: feature, Priority : High

#88 🔀 :: 87-master로 머지하기전에 이것저것 수정
  src/main/kotlin/com/dotori/v2/domain/email/presentation/EmailController.kt
  src/main/kotlin/com/dotori/v2/domain/email/service/SignupEmailSendService.kt
  src/main/kotlin/com/dotori/v2/domain/email/service/impl/SignupEmailSendServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/massage/exception/NotMassageCancelDayException.kt
  src/main/kotlin/com/dotori/v2/domain/member/presentation/MemberController.kt
  src/main/kotlin/com/dotori/v2/global/config/security/SecurityConfig.kt
Labels: Priority : Low

#92 🔀 :: 90 - 리펙토링
  src/main/kotlin/com/dotori/v2/domain/email/service/impl/EmailSendServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/email/service/impl/SignupEmailSendServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageMemberResDto.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt
Labels: bug, Priority : Critical

#89 🔀 컬럼명이 달라 작동안하던 버그 해결
  src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
Labels: bug, Priority : Critical

#94 🔀 :: 93 - 이메일 인증 없이 비번 변경
  src/main/kotlin/com/dotori/v2/domain/member/presentation/AuthController.kt
  src/main/kotlin/com/dotori/v2/domain/member/presentation/MemberController.kt
  src/main/kotlin/com/dotori/v2/domain/member/service/ChangeAuthPasswordService.kt
  src/main/kotlin/com/dotori/v2/domain/member/service/impl/ChangeAuthPasswordServiceImpl.kt
  src/test/kotlin/com/dotori/v2/domain/member/controller/ChangePasswordControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/member/controller/LogoutControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/member/controller/RefreshTokenControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/member/controller/WithdrawalControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyMemberNameServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyStuNumServiceTest.kt
Labels: feature, Priority : High

#97 🔀 :: 96-메인 페이지 Response 값 수정
  src/main/kotlin/com/dotori/v2/domain/board/domain/entity/Board.kt
  src/main/kotlin/com/dotori/v2/domain/board/domain/repository/BoardRepository.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/data/dto/BoardDto.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/CreateBoardServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardDetailServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/main_page/presentation/dto/res/BoardAlarmResDto.kt
  src/main/kotlin/com/dotori/v2/domain/main_page/service/impl/BoardAlarmServiceImpl.kt
  src/test/kotlin/com/dotori/v2/domain/board/controller/CreateBoardControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/main_page/controller/BoardAlarmControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/main_page/service/BoardAlarmServiceTest.kt
Labels: feature, Priority : High

#100 🔀 :: 99 - 자습 인원 조정 API추가
  src/main/kotlin/com/dotori/v2/domain/self_study/domain/entity/SelfStudyCount.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/admin/AdminSelfStudyController.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/req/SelfStudyLimitReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/res/SelfStudyInfoResDto.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/member/MemberSelfStudyController.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/ChangeSelfStudyLimitService.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyByStuNumAndNameService.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/ApplySelfStudyServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/ChangeSelfStudyLimitServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumAndNameServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyInfoServiceImpl.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/ApplySelfStudyControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/CancelSelfStudyControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyInfoControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyMemberNameControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyRankControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyStuNumControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyInfoServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyMemberNameServiceTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyStuNumServiceTest.kt
Labels: feature, Priority : High

#102 timeZone세팅
  src/main/kotlin/com/dotori/v2/V2Application.kt
Labels: feature, Priority : Critical

#105 🔀 :: 104 - 자습 체크 API
  src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotSelfStudyAppliedException.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/admin/AdminSelfStudyController.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/req/SelfStudyCheckReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/UpdateSelfStudyCheckService.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/UpdateSelfStudyCheckServiceImpl.kt
  src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/ApplySelfStudyControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/CancelSelfStudyControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyInfoControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyRankControllerTest.kt
Labels: feature, Priority : High

#107 🔀 :: 106-안마의자 제한 설정 추가
  src/main/kotlin/com/dotori/v2/domain/massage/domain/entity/MassageCount.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/admin/AdminMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/councillor/CouncillorMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/developer/DeveloperMassageController.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/req/MassageLimitReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageInfoResDto.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/UpdateMassageLimitService.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/GetMassageInfoServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/UpdateMassageLimitServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/domain/entity/SelfStudyCount.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/req/SelfStudyLimitReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/res/SelfStudyInfoResDto.kt
Labels: feature, Priority : High

#110 🔀 :: 109-규정위반 삭제하기
  src/main/kotlin/com/dotori/v2/domain/rule/exception/NotFoundRuleException.kt
  src/main/kotlin/com/dotori/v2/domain/rule/presentation/admin/AdminRuleController.kt
  src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/dto/RuleDto.kt
  src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/res/RuleListResDto.kt
  src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/res/RuleResDto.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/DeleteRuleService.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/impl/DeleteRuleServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindAdminRuleServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindAllAdminRuleServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindCouncillorServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindDeveloperRuleServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindMemberRuleServiceImpl.kt
  src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt
Labels: feature, Priority : High

#113 🔀 :: 112 - 안마의자 신청/취소 시간대 검증 로직 변경
  src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt
Labels: bug, Priority : Critical

#111 🔀 :: 전체적으로 학생정보 리팩토링
  src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt
  src/main/kotlin/com/dotori/v2/domain/member/presentation/data/dto/MemberDto.kt
  src/main/kotlin/com/dotori/v2/domain/rule/presentation/admin/AdminRuleController.kt
  src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/req/StudentListReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/FindAllAdminRuleService.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/FindStudentService.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindAllAdminRuleServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindStudentServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/data/res/SearchStudentListResDto.kt
  src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/SearchStudentServiceImpl.kt
Labels: feature, Priority : High

#115 🔀 :: 114 - 테스트용 계정
  src/main/kotlin/com/dotori/v2/global/config/dev/DevMemberConfig.kt
Labels: feature, Priority : High

#117 🔀 프로필 설정 안되던거 해결
  DockerfileDev
  DockerfileProd
Labels: bug, Priority : High

#119 🔀 :: 118 - 게발객체 비번 변경
  src/main/kotlin/com/dotori/v2/global/config/dev/DevMemberConfig.kt
Labels: bug, Priority : High

#123 🔀 :: 마스터에서만 작동해요 ㅠ
  .github/workflows/ci.yml
  .github/workflows/develop-cd.yml
  .github/workflows/master-cd.yml
Labels: bug

#122 🔀 빠르게 머지
  .github/workflows/ci.yml
  .github/workflows/develop-cd.yml
  .github/workflows/master-cd.yml
Labels: bug

#128 🔀 :: 127 - 안마의자 신청 조회에서 자습신청 조회가 됨
  src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageRepository.kt
Labels: bug, Priority : Critical

#137 🔀 :: 136 - 안마의자 예외 제대로 적용
  src/main/kotlin/com/dotori/v2/domain/massage/service/impl/GetMassageInfoServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyInfoServiceImpl.kt
Labels: bug, Priority : Critical

#141 🔀 :: 140-공지사항 반환값 수정
  src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/BoardResDto.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/DetailBoardResDto.kt
  src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/ListBoardResDto.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardDetailServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardsServiceImpl.kt
Labels: Priority : High
