Repository Team-Ampersand/Dotori-server-V2, pull requests merged in 2023-04, with the labels that each got.

#142 🔀 :: 음악신청 일요일 풀기
  src/main/kotlin/com/dotori/v2/domain/music/service/impl/ApplyMusicServiceImpl.kt
Labels: bug, Priority : Critical

#143 develop master로
  src/main/kotlin/com/dotori/v2/domain/board/domain/repository/BoardRepository.kt
  src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardsServiceImpl.kt
  src/main/kotlin/com/dotori/v2/domain/music/service/impl/ApplyMusicServiceImpl.kt
Labels: Priority : Critical

#155 🔀 :: 154 - 자습,안마의자 신청,취소 errorMessage 수정
  src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt
Labels: Priority : High

#159 🔀 :: 158 - 자습 schedule객체가 count를 초기화 안하고 있었음
  src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/UpdateSelfStudyStatusServiceImpl.kt
Labels: bug, Priority : Critical

#162 🔀 :: 161 - 자습, 안마의자 신청인원이 유동적으로 변할 수 있어서 에러 메세지 수정
  src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt
Labels: bug, Priority : High

#164 🔀 :: 로그인 되지 않았을때 비번병경할때 현재 비밀번호를 입력하지 않고 변경하게끔 수정
  src/main/kotlin/com/dotori/v2/domain/member/presentation/data/req/NewPasswordReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/member/presentation/data/req/NoAuthNewPasswordReqDto.kt
  src/main/kotlin/com/dotori/v2/domain/member/service/impl/ChangePasswordServiceImpl.kt
  src/test/kotlin/com/dotori/v2/domain/member/controller/ChangePasswordControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/member/service/ChangePasswordServiceTest.kt
Labels: Priority : High

#177 🔀 :: 176 - signupController 테스트 코드
  src/test/kotlin/com/dotori/v2/domain/member/controller/SignupControllerTest.kt
Labels: feature, Priority : Medium

#181 🔀 :: 180 - 비밀번호 변경 테스트 코드 커버리지 높이기
  src/test/kotlin/com/dotori/v2/domain/member/service/ChangePasswordServiceTest.kt
Labels: feature, Priority : Medium

#183 🔀 :: 182 - 자습신청 서비스 테스트코드 리펙토링
  src/test/kotlin/com/dotori/v2/domain/self_study/service/ApplySelfStudyServiceTest.kt
Labels: Priority : Medium

#186 🔀 :: 185 - 자습 취소 서비스 테스트코드 리펙토링
  src/test/kotlin/com/dotori/v2/domain/self_study/service/CancelSelfStudyServiceTest.kt
Labels: Priority : Medium

#188 🔀 :: 187 - 자습 인원변경 테스트 코드
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/ChangeSelfStudyLimitControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/ChangeSelfStudyLimitServiceTest.kt
Labels: feature, Priority : Medium

#190 🔀 :: 189 - 자습 체크 API 테스트 코드
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/UpdateSelfStudyCheckControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/UpdateSelfStudyCheckServiceTest.kt
Labels: feature, Priority : Medium

#192 🔀 :: 191 - 자습 금지 테스트 코드 작성
  src/test/kotlin/com/dotori/v2/domain/self_study/controller/BanSelfStudyControllerTest.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/service/BanSelfStudyServiceTest.kt
Labels: feature, Priority : Medium

#194 🔀 :: 193 - 자습 상태를 일괄적으로 변경하는 서비스 테스트 코드
  src/test/kotlin/com/dotori/v2/domain/self_study/service/UpdateSelfStudyStatusServiceTest.kt
Labels: feature, Priority : Medium

#198 🔀 :: 197 - codeowners 세팅
  .github/CODEOWNERS
Labels: feature, Priority : Low

#200 🔀 :: 199 - FindSelfStudyCountUtil 테스트 코드 작성
  src/test/kotlin/com/dotori/v2/domain/self_study/util/FindSelfStudyCountUtilTest.kt
Labels: feature, Priority : Medium

#202 🔀 :: 201 - 20분부터 신청가능하도록 수정
  src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt
Labels: bug, Priority : Critical

#204 🔀 :: 203 - 자습신청 시간 검증 객체 테스트 코드
  src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt
  src/test/kotlin/com/dotori/v2/domain/self_study/util/ValidaDayOfWeekAndHourTest.kt
Labels: feature, Priority : Medium
